In [69]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('../data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
# convert the 'date_added' column to datetime format and extract year and month features
df["date_added"] = pd.to_datetime(df["date_added"], errors='coerce')

# Handle missing date_added (fill with median date)
df['date_added'] = df['date_added'].fillna(df['date_added'].median())

df["year_added"] = df["date_added"].dt.year.astype('Int64')
df["month_added"] = df["date_added"].dt.month.astype('Int64')

In [71]:
# content age feature
current_year = pd.Timestamp.now().year
df["content_age"] = current_year - df["release_year"]

In [72]:
# primary genre feature
df['primary_genre'] = df['listed_in'].str.split(',').str[0]

In [73]:
df['duration_minutes'] = df['duration'].str.extract('(\d+)')
df['duration_minutes'] = pd.to_numeric(df['duration_minutes'], errors='coerce').astype('Int64')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\PRASHANT\AppData\Local\Temp\ipykernel_5772\2304914119.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['duration_minutes'] = df['duration'].str.extract('(\d+)')

In [74]:
# region feature
df['primary_country'] = df['country'].str.split(',').str[0]

,show_id,type,title,director,casts,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,content_age,primary_genre,duration_minutes,primary_country,is_movie
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,6,Documentaries,90,United States,1
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,5,International TV Shows,2,South Africa,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,5,Crime TV Shows,1,Unknown,0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,5,Docuseries,1,Unknown,0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,5,International TV Shows,2,India,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,s96,TV Show,The Circle,NaN,Michelle Buteau,"United States, United Kingdom",2021-09-08,2021,TV-MA,3 Seasons,Reality TV,Status and strategy collide in this social exp...,2021,9,5,Reality TV,3,United States,0
96,s97,Movie,If I Leave Here Tomorrow: A Film About Lynyrd ...,Stephen Kijak,"Ronnie Van Zandt, Gary Rossington, Allen Colli...",United States,2021-09-07,2018,TV-MA,97 min,"Documentaries, Music & Musicals","Using interviews and archival footage, this do...",2021,9,8,Documentaries,97,United States,1
97,s98,TV Show,Kid Cosmic,NaN,"Jack Fisher, Tom Kenny, Amanda C. Miller, Kim ...",United States,2021-09-07,2021,TV-Y7,2 Seasons,"Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",A boy's superhero dreams come true when he fin...,2021,9,5,Kids' TV,2,United States,0
98,s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,2021-09-07,2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...,2021,9,5,British TV Shows,1,United Kingdom,0
99,s100,TV Show,On the Verge,NaN,"Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...","France, United States",2021-09-07,2021,TV-MA,1 Season,"TV Comedies, TV Dramas","Four women — a chef, a single mom, an heiress ...",2021,9,5,TV Comedies,1,France,0

In [75]:
# binary indicator for movie
df["is_movie"] = np.where(df["type"] == "Movie", 1, 0)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\PRASHANT\AppData\Local\Temp\ipykernel_5772\2304914119.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['duration_minutes'] = df['duration'].str.extract('(\d+)')

In [77]:
df.to_csv("../data/netflix_featured.csv", index=False)
df.head()

,show_id,type,title,director,casts,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,content_age,primary_genre,duration_minutes,primary_country,is_movie
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,6,Documentaries,90,United States,1
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,5,International TV Shows,2,South Africa,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,5,Crime TV Shows,1,Unknown,0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,5,Docuseries,1,Unknown,0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,5,International TV Shows,2,India,0

In [79]:
df.isnull().sum()

show_id             0
type                0
title               0
director            0
casts               0
country             0
date_added          0
release_year        0
rating              4
duration            3
listed_in           0
description         0
year_added          0
month_added         0
content_age         0
primary_genre       0
duration_minutes    3
primary_country     0
is_movie            0
dtype: int64